import { LangSelect } from '@/shared/components/LangSelect/LangSelect'
import { useRouterLocaleDefinition } from '@/shared/hooks/useRouterLocaleDefinition'
import { en } from '@/shared/locales/en'
import { ru } from '@/shared/locales/ru'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import { useRouter } from 'next/router'

import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const t = useRouterLocaleDefinition()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content={'Generated by create next app'} name={'description'} />
        <meta content={'width=device-width, initial-scale=1'} name={'viewport'} />
        <link href={'/favicon.ico'} rel={'icon'} />
      </Head>
      <div>{<LangSelect />}</div>
      <main>
        <div>{t.title}</div>
        <div>{t.passwordRecoveryPage.title}</div>
        <div>DEPLOYING</div>
      </main>
    </>
  )
}
