import { Inter } from 'next/font/google'
import Head from 'next/head'
import Link from 'next/link'

import styles from './Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content={'Generated by create next app'} name={'description'} />
        <meta content={'width=device-width, initial-scale=1'} name={'viewport'} />
        <link href={'/favicon.ico'} rel={'icon'} />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Link href={'/'}>Main</Link>
        <Link href={'/linkFirst'}>List First</Link>
        <Link href={'/linkSecond'}>List Second</Link>
      </main>
    </>
  )
}
