import React from 'react'

import Head from 'next/head'

type MetaHeadProps = {
  title: string
}

export const MetaHead = (props: MetaHeadProps) => {
  const { title } = props

  return (
    <Head>
      <title>{title}</title>
      <meta content={'Generated by create next app'} name={'description'} />
      <meta content={'width=device-width, initial-scale=1'} name={'viewport'} />
      <link href={'/favicon.svg'} rel={'icon'} />
    </Head>
  )
}
