import { browserTheme } from '@/shared/utils/browserTheme'
import Head from 'next/head'

interface IProps {
  title: string
}

export const MetaHead = ({ title }: IProps) => {
  const favicon = browserTheme() ? '/lightFavicon.svg' : '/darkFavicon.svg'

  return (
    <Head>
      <title>{title}</title>
      <meta content={'Generated by create next app'} name={'description'} />
      <meta content={'width=device-width, initial-scale=1'} name={'viewport'} />
      <link href={favicon} rel={'icon'} />
    </Head>
  )
}
